name: Release

on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: true

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.release.outputs['version'] }}
      pr: ${{ steps.release.outputs['pr'] }}
      releases_created: ${{ steps.release.outputs['releases_created'] }}

    steps:
      - name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        with:
            token: ${{ secrets.RELEASE_TOKEN }}
            command: manifest
            config-file: .github/release-please/config.json
            manifest-file: .github/release-please/manifest.json


      - name: Show output from release-please
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq

  #bump-version:
  #  if: needs.release-please.outputs.pr != null
  #  runs-on: builder
  #  needs:
  #    - release-please

  #  permissions:
  #    contents: write

  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #      with:
  #        ref: ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}

  #    - name: Get version
  #      id: version
  #      run: |
  #        version="$(jq -r '.[]' .github/release-please/manifest.json)"
  #        echo "version=${version}" >> $GITHUB_OUTPUT

  #    - name: Setup Rust toolchain
  #      uses: actions-rust-lang/setup-rust-toolchain@v1

  #    - name: Install cargo-edit
  #      uses: baptiste0928/cargo-install@v3.0.0
  #      with:
  #        crate: cargo-edit

  #    - name: Set version
  #      run: cargo set-version ${{ steps.version.outputs.version }}

  #    - name: Commit version bump
  #      uses: stefanzweifel/git-auto-commit-action@v5
  #      with:
  #        commit_message: "chore: Bump version to ${{ steps.version.outputs.version }}"
  #        branch: ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}
